reload "user.plugins"
reload "user.harpoon"
reload "user.keymaps"
reload "user.whichkey"
reload "user.nvimtree"
reload "user.options"
reload "user.telescope"
reload "user.colorizer"
reload "user.lsp"
reload "user.git"
reload "user.neogit"


lvim.colorscheme = "tokyonight"
vim.g.tokyonight_style = "storm"
